M48
; DRILL file {KiCad (6.0.0)} date Fri Jul  8 19:14:15 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-08T19:14:15+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X5.193Y-43.103
X5.193Y-48.883
T2
X1.428Y-80.975
T3
X6.906Y-57.693
X6.906Y-69.123
T0
M30
